name: Test, build and deploy Mastermind Web Compiler

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!*.md"
      - "!./compiler/programs/*.mmi"

jobs:
  test_build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
      - uses: jetli/wasm-pack-action@v0.4.0
      - run: cd compiler && cargo test
      - run: cd compiler && wasm-pack build --release --target web
      - run: yarn
      - run: yarn build:grammar
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOST_PIXELS_PROD }}
          projectId: lost-pixels-prod
          target: mastermind
          channelId: live
