name: Dev staging pipeline

on:
  push:
    branches:
      - dev
    paths:
      - "**"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - uses: jetli/wasm-pack-action@v0.4.0

      - name: Test compiler
        run: cargo test
        working-directory: compiler

      - name: Build compiler for WASM
        run: wasm-pack build --release --target web
        working-directory: compiler

      - name: Node dependencies
        run: yarn install --frozen-lockfile

      - name: Build grammar
        run: yarn build:grammar

      - name: Build web app
        run: yarn build

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LOST_PIXELS_PROD }}
          projectId: lost-pixels-prod
          # "target" is defined in firebase.json and .firebaserc, the latter controlling which firebase site to deploy to
          target: mastermind-staging
          channelId: live
